# Generated by Django 6.0.2 on 2026-02-07 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_school_application',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_school_applications', to='users.parentprofile'),
        ),
        migrations.AddField(
            model_name='parent_school_application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_school_applications', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='parent_school_application',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_school_applications', to='schools.school'),
        ),
    ]
