# Generated by Django 6.0.2 on 2026-02-26 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_parent_school_application_created_at_and_more'),
        ('users', '0003_alter_user_managers_alter_schooladminprofile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school'),
        ),
    ]
