# Generated by Django 6.0.2 on 2026-02-07 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_initial'),
        ('uniform_orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniform_assignment',
            name='tailor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniform_assignment', to='users.tailorprofile'),
        ),
        migrations.AddField(
            model_name='uniform_order',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniform_order', to='users.parentprofile'),
        ),
        migrations.AddField(
            model_name='uniform_order',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniform_order', to='schools.school'),
        ),
        migrations.AddField(
            model_name='uniform_assignment',
            name='uniform_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniform_assignment', to='uniform_orders.uniform_order'),
        ),
    ]
