# Generated by Django 6.0.2 on 2026-02-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniform_assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('started', 'Started'), ('halfway', 'Halfway Done'), ('complete', 'Complete')], default='pending', max_length=20),
        ),
    ]
