# Generated by Django 6.0.2 on 2026-02-07 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tailors', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor_school_request',
            name='tailor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailorschoolrequest', to='users.tailorprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='tailor_school_request',
            unique_together={('tailor', 'school')},
        ),
    ]
